// src/components/Home.js
import React from 'react';

function Home() {
  return (
    <div>
      <h1>SBOM Runtime Dependency Testing</h1>
      <p>This application is designed to test how the Continuous SBOM extension captures runtime dependencies.</p>
      
      <h2>Test Scenarios</h2>
      <ul>
        <li>
          <strong>CDN Loader Test:</strong> Loads a library (Moment.js) directly from a CDN when a button is clicked.
        </li>
        <li>
          <strong>Dynamic Import Test:</strong> Uses ES6 dynamic imports to load Chart.js only when needed.
        </li>
        <li>
          <strong>Data Formatter (Lazy Load):</strong> A route-based lazy-loaded component that uses Lodash.
        </li>
        <li>
          <strong>Data Visualizer (Lazy Load):</strong> A route-based lazy-loaded component that uses D3.js.
        </li>
      </ul>
      
      <h2>How to Test</h2>
      <ol>
        <li>Run the application with the SBOM monitoring script enabled.</li>
        <li>Click through each test case and observe the dynamic-dependencies.json file.</li>
        <li>Compare with a static SBOM generated by the GitHub workflow.</li>
      </ol>
    </div>
  );
}

export default Home;